@server = http://localhost:3000
@newmatchid = 2f648c72-45ac-4be0-a259-12340f3472f1


### test the app
GET {{server}}/api/

### read all teams
GET {{server}}/api/team

### read all teams
GET {{server}}/api/status

### read a specific team
GET {{server}}/api/team/25ae03be-8b74-4443-9b3c-71737566c567

### read all matches
GET {{server}}/api/match

### read all matches
GET {{server}}/api/ranking

### read all match with id
GET {{server}}/api/match/{{newmatchid}}

### create a new match
POST {{server}}/api/match
Content-Type: application/json

  {
    "id": "{{newmatchid}}",
    "startDate": "2023-04-06",
    "matchDay": 15,
    "team1": "d389b8d3-254a-4925-8fb5-667520035eaf",
    "team2": "9a664089-2e4b-4c56-af71-5b96d2c9d187",
    "finished": false,
    "goals1": -1,
    "goals2": -1
  }

### UPDATE match with a new data
PATCH {{server}}/api/match/{{newmatchid}}
Content-Type: application/json

  {
    "startDate": "2023-04-10"
  }

### add a result to a match
PUT {{server}}/api/addresult
Content-Type: application/json

  {
    "id": "{{newmatchid}}",
    "goals1": 8,
    "goals2": 7
  }

### delete match with id
DELETE {{server}}/api/match/{{newmatchid}}


### options of root
OPTIONS {{server}}/api/

### Head of root
HEAD {{server}}/api/


### GET of root
GET {{server}}/api/

### options of match endpoint
OPTIONS {{server}}/api/match/


### find matches
GET {{server}}/api/findmatches?term=FC


### find matchew with id
GET {{server}}/api/findmatches?term=eintracht


### find matchew with id
GET {{server}}/api/findteams?term=frank